version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postcss
    versions:
    - 7.0.35
    - 8.2.10
    - 8.2.12
    - 8.2.9
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.4.0
    - 1.4.1
    - 1.5.0
  - dependency-name: sass
    versions:
    - 1.32.11
  - dependency-name: react-spring
    versions:
    - 9.1.1
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.2
  - dependency-name: file-loader
    versions:
    - 6.2.0
  - dependency-name: "@fortawesome/react-fontawesome"
    versions:
    - 0.1.14
